trigger:
- main

name: Deploy-$(Date:yyyyMMdd)-$(Rev:r)

parameters:
- name: azureServiceConnection
  type: string
  default: 'sp-portal-js-jagz'

variables:
  resourceGroupName: 'rg-portal-js-jagz'
  location: 'Canada Central'
  templateFile: 'bicep/main.bicep'
  parametersFile: 'bicep/main.bicepparam'
  parametersFile: 'bicep/main.bicepparam'

pool:
  name: 'Default'   

steps:
- task: AzurePowerShell@5
  displayName: 'Deploy Bicep to Resource Group'
  inputs:
    azureSubscription: ${{ parameters.azureServiceConnection }}
    ScriptType: 'InlineScript'
    pwsh: true   # 👈 ensures it uses PowerShell Core on Linux
    Inline: |
      Write-Host "Deploying Bicep to Resource Group: $(resourceGroupName)"

      New-AzResourceGroupDeployment `
        -ResourceGroupName $(resourceGroupName) `
        -TemplateFile $(templateFile) `
        -TemplateParameterFile $(parametersFile) `
        -Mode Incremental `
        -Verbose
    azurePowerShellVersion: LatestVersion
