# Simple Bicep Deployment Pipeline

trigger:
- main

name: Deploy-$(Date:yyyyMMdd)-$(Rev:r)

parameters:
- name: azureServiceConnection
  type: string
  default: 'sp-portal-js-jagz'

variables:
  resourceGroupName: 'rg-portal-js-jagz'
  location: 'Canada Central'
  templateFile: 'bicep/main.bicep'
  parametersFile: 'bicep/main.bicepparam'

pool:
  name: default

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Create Resource Group'
  inputs:
    azureSubscription: '${{ parameters.azureServiceConnection }}'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name $(resourceGroupName) --location "$(location)"

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Bicep Template'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    csmParametersFile: '$(parametersFile)'
    deploymentMode: 'Incremental'
    deploymentName: 'Deploy-$(Build.BuildNumber)'
    connectedServiceName: '${{ parameters.azureServiceConnection }}'