trigger:
- main

name: Deploy Bicep files

parameters:
- name: azureServiceConnection
  type: string
  default: 'sp-portal-js-jagz'

variables:
  resourceGroupName: 'rg-portal-js-jagz'
  location: 'Canada Central'
  templateFile: 'bicep/main.bicep'
  parametersFile: 'bicep/main.bicepparam'

pool:
  name: default   # 👈 your self-hosted pool

steps:

- task: AzurePowerShell@5
  displayName: 'Create Resource Group if not exists'
  inputs:
    azureSubscription: ${{ parameters.azureServiceConnection }}
    ScriptType: InlineScript
    pwsh: true
    Inline: |
      $rgName = "$(resourceGroupName)"
      $loc = "$(location)"

      if (-not (Get-AzResourceGroup -Name $rgName -ErrorAction SilentlyContinue)) {
        New-AzResourceGroup -Name $rgName -Location "$loc"
        Write-Host "Resource group $rgName created in $loc."
      } else {
        Write-Host "Resource group $rgName already exists."
      }
    azurePowerShellVersion: LatestVersion


- task: AzurePowerShell@5
  displayName: 'Deploy Bicep to Resource Group'
  inputs:
    azureSubscription: ${{ parameters.azureServiceConnection }}
    ScriptType: InlineScript
    pwsh: true   # 👈 ensures it uses PowerShell Core on Linux
    Inline: |
      $rgName = "$(resourceGroupName)"
      $template = "$(templateFile)"
      $params = "$(parametersFile)"

      Write-Host "Deploying Bicep to Resource Group: $rgName"

      New-AzResourceGroupDeployment `
        -ResourceGroupName "$rgName" `
        -TemplateFile "$template" `
        -TemplateParameterFile "$params" `
        -Mode Incremental `
        -Verbose
    azurePowerShellVersion: LatestVersion
