trigger:
- main

name: Deploy Bicep files

parameters:
- name: azureServiceConnection
  type: string
  default: 'sp-portal-js-jagz'

variables:
  resourceGroupName: 'rg-portal-js-jagz'
  location: 'Canada Central'
  templateFile: 'bicep/main.bicep'
  parametersFile: 'bicep/main.bicepparam'

pool:
  name: default   

steps:

- task: AzurePowerShell@5
  displayName: 'Create Resource Group if not exists'
  inputs:
    azureSubscription: ${{ parameters.azureServiceConnection }}
    ScriptType: InlineScript
    pwsh: true
    Inline: |
      if (-not (Get-AzResourceGroup -Name $(resourceGroupName) -ErrorAction SilentlyContinue)) {
        New-AzResourceGroup -Name $(resourceGroupName) -Location $(location)
        Write-Host "Resource group $(resourceGroupName) created in $(location)."
      } else {
        Write-Host "Resource group $(resourceGroupName) already exists."
      }
    azurePowerShellVersion: LatestVersion


- task: AzurePowerShell@5
  displayName: 'Deploy Bicep to Resource Group'
  inputs:
    azureSubscription: ${{ parameters.azureServiceConnection }}
    ScriptType: 'InlineScript'
    pwsh: true   # 👈 ensures it uses PowerShell Core on Linux
    Inline: |
      Write-Host "Deploying Bicep to Resource Group: $(resourceGroupName)"

      New-AzResourceGroupDeployment `
        -ResourceGroupName $(resourceGroupName) `
        -TemplateFile $(templateFile) `
        -TemplateParameterFile $(parametersFile) `
        -Mode Incremental `
        -Verbose
    azurePowerShellVersion: LatestVersion
